SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
CREATE DATABASE IF NOT EXISTS MegaLAN;
GRANT ALL PRIVILEGES ON MegaLAN.* TO 'MegaLAN'@'%' IDENTIFIED BY 'MegaLAN';
FLUSH PRIVILEGES;
USE MegaLAN;

COMMIT;
